from __future__ import annotations

from enum import StrEnum


class TradingMode(StrEnum):
    WATCH_MODE = "WATCH_MODE"
    PAPER_MODE = "PAPER_MODE"
    LIVE_MODE = "LIVE_MODE"


class EventType(StrEnum):
    MARKET_TICK = "MARKET_TICK"
    ORDERBOOK_UPDATE = "ORDERBOOK_UPDATE"
    TRADE_UPDATE = "TRADE_UPDATE"
    BAR_CLOSED = "BAR_CLOSED"
    FEATURE_UPDATE = "FEATURE_UPDATE"
    REGIME_UPDATE = "REGIME_UPDATE"
    ORDERFLOW_UPDATE = "ORDERFLOW_UPDATE"
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    DA_VERDICT = "DA_VERDICT"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_FILLED = "ORDER_FILLED"
    POSITION_UPDATED = "POSITION_UPDATED"
    RISK_ALERT = "RISK_ALERT"
    KILL_SWITCH = "KILL_SWITCH"


class Regime(StrEnum):
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    CHOPPY = "CHOPPY"
    COMPRESSION = "COMPRESSION"
    EXPANSION = "EXPANSION"
    PANIC = "PANIC"
    MEAN_REVERT = "MEAN_REVERT"


class SessionPhase(StrEnum):
    ASIA_GRIND = "ASIA_GRIND"
    LONDON_OPEN = "LONDON_OPEN"
    OVERLAP_ACTIVE = "OVERLAP_ACTIVE"
    NY_AFTERNOON = "NY_AFTERNOON"
    DEAD_ZONE = "DEAD_ZONE"


class OrderState(StrEnum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class CertificationState(StrEnum):
    CERTIFIED = "CERTIFIED"
    CONDITIONAL = "CONDITIONAL"
    REJECTED = "REJECTED"
